name: FlareonEvents
author: EinfacheSache | Tom
website: https://einfachesache.de/discord
description: Das offizielle Flareon Events Plugin
version: '${project.version}:${buildNumber}'
main: de.einfachesache.flareonevents.FlareonEvents
api-version: '1.21.6'
softdepend: [ voicechat ]
commands:
  help:
    description: 'Hilfe zu Event-Befehlen'

  msg:
    description: 'Sende eine private Nachricht an einen Spieler'

  reply:
    description: 'Antworte dem letzten Gesprächspartner privat'

  team:
    description: 'Verwalte dein Team: einladen, auflisten, verlassen und mehr'

  recipe:
    description: 'Öffne die Rezept-GUI für Custom-Items'

  report:
    description: 'Melde einen Bug als Discord-Ticket'

  event:
    description: 'Administrative Befehle zur Event-Verwaltung'
    permission: 'event.op'

  chestloot:
    description: 'Administrative Befehle um Chestloot zu setzen'
    permission: 'event.op'

  update:
    description: 'Aktualisiere Custom-Items und lade alle Konfigurationsdateien neu'
    permission: 'event.op'

  customitem:
    description: 'Gib dir ein benutzerdefiniertes Item'
    permission: 'event.op'
    aliases: [ ci ]

  settings:
    description: 'Passe Welt- und Event-Einstellungen an (z. B. PvP, Sichtweite, Simulations-Distanz, Nether-Zugriff)'
    permission: 'event.op'
    aliases: [ ctl ]
