name: FlareonEvents
author: EinfacheSache | Tom
website: https://einfachesache.de/discord
description: Das offizielle Flareon Events Plugin
version: '1.0-SNAPSHOT'
main: de.einfachesache.flareonevents.FlareonEvents
api-version: '1.21'
softdepend: [voicechat]
commands:
  team:
    description: 'Manage your team: invite, list, leave, and more'
    aliases: [ tm, teams ]

  recipegui:
    description: 'Open the custom item recipe GUI'
    aliases: [ rg, items, customs ]

  event:
    description: 'Administrative event management commands'
    permission: 'event.op'
    aliases: [ ev ]

  update:
    description: 'Update custom items and reload all configuration files'
    permission: 'event.op'
    aliases: [ devreload ]

  customitem:
    description: 'Command to give yourself a custom item'
    permission: 'event.op'
    aliases: [ ci ]
