name: FlareonEvents
version: '1.0-SNAPSHOT'
main: de.einfachesache.flareonEvents.FlareonEvents
api-version: '1.21'
commands:
  event:
    description: 'Event Manage Command'
    permission: 'event.op'
    aliases: [ ev ]
  customitem:
    description: 'Custom Item Command'
    permission: 'event.op'
    aliases: [ ci ]
  recipegui:
    description: 'Open Recipe-Gui'
    aliases: [ rg ]

