name: FlareonEvents
author: EinfacheSache | Tom
website: https://einfachesache.de/discord
description: Das offizielle Flareon Events Plugin
version: '1.0-SNAPSHOT'
main: de.einfachesache.flareonEvents.FlareonEvents
api-version: '1.21'
commands:
  event:
    description: 'Event Manage Command'
    permission: 'event.op'
    aliases: [ ev ]
  customitem:
    description: 'Custom Item Command'
    permission: 'event.op'
    aliases: [ ci ]
  recipegui:
    description: 'Open Recipe-Gui'
    aliases: [ rg, items, customs ]
  update:
    description: 'Update Custom-Items'
    permission: 'event.op'
