name: Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -V clean package

      # Release neu erzeugen/aktualisieren → frische Source-ZIPs
      - name: Create or update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Build"
          body: |
            Automated build from ${{ github.repository }} @ ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # JAR ins Release anhängen
      - name: Upload JAR asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/FlareonEvents-1.0-SNAPSHOT.jar
          asset_name: FlareonEvents-1.0-SNAPSHOT.jar
          tag: latest
          overwrite: true