name: Build

on:
  push:
    branches: [ main, master ]
    tags: [ "*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # nötig für Release-Upload bei Tags

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -V clean package

      # (Optional) Artefakt im Actions-Tab für Nicht-Tag-Builds
      # -> bleibt immer ZIP; kannst du entfernen, wenn du es nicht brauchst
      - name: Upload artifact (Actions tab)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: FlareonEvents
          path: target/FlareonEvents-1.0-SNAPSHOT.jar
          if-no-files-found: error
          overwrite: true

      # JAR direkt ans Release anhängen, sobald ein Tag gebaut wird
      - name: Upload JAR to GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: target/FlareonEvents-1.0-SNAPSHOT.jar
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}