name: Build

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -V clean package

      - name: Upload JAR to 'latest' Release
        if: github.event_name == 'push'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/FlareonEvents-1.0-SNAPSHOT.jar
          asset_name: FlareonEvents-1.0-SNAPSHOT.jar
          tag: latest
          release_name: "Latest Build"
          overwrite: true
          body: |
            Automated build from ${{ github.repository }} @ ${{ github.sha }}.
