name: Build

on:
  push:
    branches: [ main, master ]
    tags: [ "*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn -B -V clean package

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: FlareonEvents-jar
          path: |
            target/*.jar
          if-no-files-found: error
